name: Release
on:
  workflow_dispatch:
    branch:
      - master
  push:
    tags:
      - "*"
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create zip, upload and notify Slack
        run: |
          name=$(basename -s .git $(git config --get remote.origin.url))
          tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          curl -X POST --data-urlencode "payload={\"channel\": \"#meta-box\", \"username\": \"Bot\", \"text\": \"New version $tag for $name has been just released!\", \"icon_emoji\": \":tada:\"}" ${{ secrets.SLACK_WEBHOOK }}